# List of memecoins
MEMECOINS = [
    "DOGE-USDT", "1000PEPE-USDT", "FLOKI-USDT", "SHIB-USDT", "1000BONK-USDT",
    "WIF-USDT", "TURBO-USDT", "MEME-USDT", "1000CHEEMS-USDT", "1000CAT-USDT"
]

# List of all symbols
ALL_SYMBOLS = list(set([
    "AVAX-USDT", "BTC-USDT", "ETH-USDT", "SOL-USDT", "OP-USDT",
    "BNB-USDT", "XRP-USDT", "LTC-USDT", "ADA-USDT",
    "DOGE-USDT", "ATOM-USDT", "SEI-USDT", "JTO-USDT", "MANTA-USDT",
    "UNI-USDT", "AAVE-USDT", "SNX-USDT", "GALA-USDT", "INJ-USDT",
    "LINK-USDT", "SUI-USDT", "STRK-USDT", "TIA-USDT", "TRX-USDT",
    "WLD-USDT", "ARB-USDT", "PEOPLE-USDT", "SAND-USDT", "SEI-USDT",
    "APT-USDT", "NEAR-USDT", "FTM-USDT"
] + MEMECOINS))